% %%% plotting loss of balance upon lesioning PCUN%%%%%
% clearvars -except wEI;
% load sim_hc.mat
% clear frN;
% simTime = 10*1000;
% [fc1,frN1,wEI1,cur1] = DMF_lesioned('../../data/connectivity_68/lesioned/sc_24_PCUN_nn1.hdf5',false,false,simTime,1,0.6,0.001,[24],wEI,true);
% [fc2,frN2,wEI2,cur2] = DMF_lesioned('../../data/connectivity_68/lesioned/sc_24_PCUN_nn1.hdf5',true,false,simTime,1,0.6,0.001,[24],wEI,true);
% curm1 = mean(cur1(1000:end,:),1);
% curm2 = mean(cur2(1000:end,:),1);
% abscurm1 = abs(curm1 + 0.026);
% abscurm2 = abs(curm2 + 0.026);
% abscurm1(24) = 0;
% abscurm2(24) = 0;
% subplot(1,2,1);barh(abscurm1);
% hold on;
% xlim([0 0.025])
% plot([0.005 0.005],[0 70],'Color','r')
% ylabel('Area ID')
% xlabel('E-I balance test condition*')
% set(gca,'YTick',1:2:68)
% box off;
% subplot(1,2,2);barh(abscurm2);
% hold on;
% xlim([0 0.025])
% plot([0.005 0.005],[0 70],'Color','r')
% ylabel('Area ID')
% xlabel('E-I balance test condition*')
% set(gca,'YTick',1:2:68)
% box off;
% set(gcf,'PaperPosition',[0 0 5 10])
% print(gcf,'-dpng','../../reports/balance_loss_lPCUN_24_v2.png')
% while(true)
%     clear;
%     scPaths = {'sc_1_rBSTS_nn5.hdf5',...
%     'sc_2_rCAC_nn5.hdf5',...
%     'sc_3_rCMF_nn5.hdf5',...
%     'sc_4_rCUN_nn5.hdf5',...
%     'sc_5_rENT_nn5.hdf5',...
%     'sc_6_rFP_nn5.hdf5',...
%     'sc_7_rFUS_nn5.hdf5',...
%     'sc_8_rIP_nn5.hdf5',...
%     'sc_9_rIT_nn5.hdf5',...
%     'sc_10_rISTC_nn5.hdf5',...
%     'sc_11_rLOCC_nn5.hdf5',...
%     'sc_12_rLOF_nn5.hdf5',...
%     'sc_13_rLING_nn5.hdf5',...
%     'sc_14_rMOF_nn5.hdf5',...
%     'sc_15_rMT_nn5.hdf5',...
%     'sc_16_rPARC_nn5.hdf5',...
%     'sc_17_rPARH_nn5.hdf5',...
%     'sc_18_rPOPE_nn5.hdf5',...
%     'sc_19_rPORB_nn5.hdf5',...
%     'sc_20_rPTRI_nn5.hdf5',...
%     'sc_21_rPCAL_nn5.hdf5',...
%     'sc_22_rPSTC_nn5.hdf5',...
%     'sc_23_rPC_nn5.hdf5',...
%     'sc_24_rPREC_nn5.hdf5',...
%     'sc_25_rPCUN_nn5.hdf5',...
%     'sc_26_rRAC_nn5.hdf5',...
%     'sc_27_rRMF_nn5.hdf5',...
%     'sc_28_rSF_nn5.hdf5',...
%     'sc_29_rSP_nn5.hdf5',...
%     'sc_30_rST_nn5.hdf5',...
%     'sc_31_rSMAR_nn5.hdf5',...
%     'sc_32_rTP_nn5.hdf5',...
%     'sc_33_rTT_nn5.hdf5',...
%     'sc_34_lBSTS_nn5.hdf5',...
%     'sc_35_lCAC_nn5.hdf5',...
%     'sc_36_lCMF_nn5.hdf5',...
%     'sc_37_lCUN_nn5.hdf5',...
%     'sc_38_lENT_nn5.hdf5',...
%     'sc_39_lFP_nn5.hdf5',...
%     'sc_40_lFUS_nn5.hdf5',...
%     'sc_41_lIP_nn5.hdf5',...
%     'sc_42_lIT_nn5.hdf5',...
%     'sc_43_lISTC_nn5.hdf5',...
%     'sc_44_lLOCC_nn5.hdf5',...
%     'sc_45_lLOF_nn5.hdf5',...
%     'sc_46_lLING_nn5.hdf5',...
%     'sc_47_lMOF_nn5.hdf5',...
%     'sc_48_lMT_nn5.hdf5',...
%     'sc_49_lPARC_nn5.hdf5',...
%     'sc_50_lPARH_nn5.hdf5',...
%     'sc_51_lPOPE_nn5.hdf5',...
%     'sc_52_lPORB_nn5.hdf5',...
%     'sc_53_lPTRI_nn5.hdf5',...
%     'sc_54_lPCAL_nn5.hdf5',...
%     'sc_55_lPSTC_nn5.hdf5',...
%     'sc_56_lPC_nn5.hdf5',...
%     'sc_57_lPREC_nn5.hdf5',...
%     'sc_58_lPCUN_nn5.hdf5',...
%     'sc_59_lRAC_nn5.hdf5',...
%     'sc_60_lRMF_nn5.hdf5',...
%     'sc_61_lSF_nn5.hdf5',...
%     'sc_62_lSP_nn5.hdf5',...
%     'sc_63_lST_nn5.hdf5',...
%     'sc_64_lSMAR_nn5.hdf5',...
%     'sc_65_lTP_nn5.hdf5',...
%     'sc_66_lTT_nn5.hdf5',...    
%     };
%     t = load('../../results/66/optimalG_hag_66_resampled_fic_dt1_sigma0.001_8mins_EI.mat');
%     wEI = t.wEI{16,1};
%     clearvars -except wEI scPaths;
% %     idxs_alstott = [[25 2 8 31 30 9 28 3 18 11 24] [25 2 8 31 30 9 28 3 18 11 24] + 33];
%     idxs = [1;3;5;7;8;9;11;15;17;18;19;20;21;22;24;27;30;31;32;33];
%     idxs_alstott = [idxs;idxs+33];
%     scEmpPath = '../../data/connectivity_998/Hagmann_998.hdf5';
%     scEmp = h5read(scEmpPath,'/C_resampled');
%     [commStrucSCEmp_998,modulSCEmp_998] = community_louvain(scEmp,1);
%     partCoefSCEmp_998 = participation_coef(scEmp,commStrucSCEmp_998,1);
%     partCoefSCEmp  = zeros(length(idxs_alstott),1);
%     simTime = 10*1000;
%     balLoss = zeros(length(idxs_alstott),1);
%     for i = 1:length(idxs_alstott)
%         nbrs = h5read(['../../data/connectivity_998/lesioned/' scPaths{i}],'/Neighbours');
%         partCoefSCEmp(i) = sum(partCoefSCEmp_998(nbrs));
%         lesionIdx = h5readatt(['../../data/connectivity_998/lesioned/' scPaths{i}],'/C_resampled','LesionIdx');
%         scPath = ['../../data/connectivity_66/lesioned/' scPaths{idxs_alstott(i)}];
%         [fc1,frN1,cur1,wEI] = DMF_lesioned(scPath,'/C_resampled_roi_avg',false,false,simTime,1,0.4,0.001,lesionIdx,wEI,true);
%         curm1 = mean(cur1(1000:end,:),1);
%         abscurm1 = abs(curm1 + 0.026);
%         abscurm1(lesionIdx) = 0;
%         balLoss(i) = length(find(abscurm1 > 0.005));
%     end
%     % figure(1);
%     % regionNames = h5read('../../data/connectivity_998/Hagmann_998.hdf5','/ROI_lbls');
%     % barh(balLoss);
%     % ylabel('Lesion Center')
%     % xlabel('No. of Areas lost E-I balance')
%     % box off;
%     % set(gca,'YTick',1:22,'YTickLabel',regionNames{idxs_alstott},'FontSize',10)
%     % set(gcf,'PaperPosition',[0 0 5 10])
%     % print(gcf,'-dpng','../../results/66/balance_loss_resampled_roi_avg.png')
%     [rho ,pVal] = corrcoef(partCoefSCEmp,balLoss);
%     rho = rho(1,2);
%     pVal = pVal(1,2);
% %     figure(2);
% %     plot(partCoefSCEmp,balLoss,'ko','MarkerFaceColor','k','MarkerSize',5);
% %     ylabel('No. of Areas lost E-I balance');
% %     xlabel('Participation Coefficient');
% %     hold on;
% %     box off;
% %     p=polyfit(partCoefSCEmp,balLoss,1);
% %     pred = polyval(p,partCoefSCEmp);
% %     plot(partCoefSCEmp,pred,'k');
% %     gtext(sprintf('r=%.2f p=%.4f',rho,pVal),'FontSize',15);
% %     set(gcf,'PaperPosition',[0 0 5 5])
% %     print(gcf,'-dpng','-r300','../../results/66/blance_loss_vs_partCoef_resampled_roi_avg.png')
%     if(pVal < 0.01)
%         break;
%     end
% end
clear;
load '../../results/66/balance_loss_vs_partCoef_resampled_roi_avg.mat';
% figure(2);
% plot(partCoefSCEmp,balLoss,'ko','MarkerFaceColor','k','MarkerSize',5);
% ylabel('No. of Areas lost E-I balance');
% xlabel('Participation Coefficient');
% hold on;
% box off;
% p=polyfit(partCoefSCEmp,balLoss,1);
% pred = polyval(p,partCoefSCEmp);
% plot(partCoefSCEmp,pred,'k');
% gtext(sprintf('r=%.2f p=%.4f',rho,pVal),'FontSize',15);
% set(gcf,'PaperPosition',[0 0 5 5])
% print(gcf,'-dpng','-r300','../../results/66/blance_loss_vs_partCoef_resampled_roi_avg.png')


figure(2);
plot(partCoefSCEmp,balLoss,'ko','MarkerFaceColor','k','MarkerSize',5);
ylabel('No. of Areas lost E-I balance','FontWeight','bold');
xlabel('Participation Coefficient','FontWeight','bold');
hold on;
box off;
p=polyfit(partCoefSCEmp,balLoss,1);
pred = polyval(p,partCoefSCEmp);
plot(partCoefSCEmp,pred,'k');
text(3,18,['r=',sprintf('%.2f',rho),', p<0.001'],'FontSize',15,'BackgroundColor',[0.3 0.7 0.7]);
xlim([2 22])
ylim([2 20])
set(gca,'XTick',2:4:22,'YTick',2:4:20,'FontSize',13)
savePath = '../../reports/figures/balance_loss_vs_partCoef_resampled_roi_avg';