% clear all;
% addpath /home/iiit/anirudh/BCT/2015_01_25' BCT'/;
% scPaths = {'sc_1_rBSTS_nn5.hdf5',...
% 'sc_2_rCAC_nn5.hdf5',...
% 'sc_3_rCMF_nn5.hdf5',...
% 'sc_4_rCUN_nn5.hdf5',...
% 'sc_5_rENT_nn5.hdf5',...
% 'sc_6_rFP_nn5.hdf5',...
% 'sc_7_rFUS_nn5.hdf5',...
% 'sc_8_rIP_nn5.hdf5',...
% 'sc_9_rIT_nn5.hdf5',...
% 'sc_10_rISTC_nn5.hdf5',...
% 'sc_11_rLOCC_nn5.hdf5',...
% 'sc_12_rLOF_nn5.hdf5',...
% 'sc_13_rLING_nn5.hdf5',...
% 'sc_14_rMOF_nn5.hdf5',...
% 'sc_15_rMT_nn5.hdf5',...
% 'sc_16_rPARC_nn5.hdf5',...
% 'sc_17_rPARH_nn5.hdf5',...
% 'sc_18_rPOPE_nn5.hdf5',...
% 'sc_19_rPORB_nn5.hdf5',...
% 'sc_20_rPTRI_nn5.hdf5',...
% 'sc_21_rPCAL_nn5.hdf5',...
% 'sc_22_rPSTC_nn5.hdf5',...
% 'sc_23_rPC_nn5.hdf5',...
% 'sc_24_rPREC_nn5.hdf5',...
% 'sc_25_rPCUN_nn5.hdf5',...
% 'sc_26_rRAC_nn5.hdf5',...
% 'sc_27_rRMF_nn5.hdf5',...
% 'sc_28_rSF_nn5.hdf5',...
% 'sc_29_rSP_nn5.hdf5',...
% 'sc_30_rST_nn5.hdf5',...
% 'sc_31_rSMAR_nn5.hdf5',...
% 'sc_32_rTP_nn5.hdf5',...
% 'sc_33_rTT_nn5.hdf5',...
% 'sc_34_lBSTS_nn5.hdf5',...
% 'sc_35_lCAC_nn5.hdf5',...
% 'sc_36_lCMF_nn5.hdf5',...
% 'sc_37_lCUN_nn5.hdf5',...
% 'sc_38_lENT_nn5.hdf5',...
% 'sc_39_lFP_nn5.hdf5',...
% 'sc_40_lFUS_nn5.hdf5',...
% 'sc_41_lIP_nn5.hdf5',...
% 'sc_42_lIT_nn5.hdf5',...
% 'sc_43_lISTC_nn5.hdf5',...
% 'sc_44_lLOCC_nn5.hdf5',...
% 'sc_45_lLOF_nn5.hdf5',...
% 'sc_46_lLING_nn5.hdf5',...
% 'sc_47_lMOF_nn5.hdf5',...
% 'sc_48_lMT_nn5.hdf5',...
% 'sc_49_lPARC_nn5.hdf5',...
% 'sc_50_lPARH_nn5.hdf5',...
% 'sc_51_lPOPE_nn5.hdf5',...
% 'sc_52_lPORB_nn5.hdf5',...
% 'sc_53_lPTRI_nn5.hdf5',...
% 'sc_54_lPCAL_nn5.hdf5',...
% 'sc_55_lPSTC_nn5.hdf5',...
% 'sc_56_lPC_nn5.hdf5',...
% 'sc_57_lPREC_nn5.hdf5',...
% 'sc_58_lPCUN_nn5.hdf5',...
% 'sc_59_lRAC_nn5.hdf5',...
% 'sc_60_lRMF_nn5.hdf5',...
% 'sc_61_lSF_nn5.hdf5',...
% 'sc_62_lSP_nn5.hdf5',...
% 'sc_63_lST_nn5.hdf5',...
% 'sc_64_lSMAR_nn5.hdf5',...
% 'sc_65_lTP_nn5.hdf5',...
% 'sc_66_lTT_nn5.hdf5',...    
% };
% 
% fcPathsFICPrior = {'fc_1_rBSTS_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_2_rCAC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_3_rCMF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_4_rCUN_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_5_rENT_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_6_rFP_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_7_rFUS_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_8_rIP_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_9_rIT_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_10_rISTC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_11_rLOCC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_12_rLOF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_13_rLING_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_14_rMOF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_15_rMT_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_16_rPARC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_17_rPARH_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_18_rPOPE_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_19_rPORB_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_20_rPTRI_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_21_rPCAL_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_22_rPSTC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_23_rPC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_24_rPREC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_25_rPCUN_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_26_rRAC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_27_rRMF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_28_rSF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_29_rSP_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_30_rST_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_31_rSMAR_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_32_rTP_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_33_rTT_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_34_lBSTS_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_35_lCAC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_36_lCMF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_37_lCUN_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_38_lENT_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_39_lFP_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_40_lFUS_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_41_lIP_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_42_lIT_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_43_lISTC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_44_lLOCC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_45_lLOF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_46_lLING_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_47_lMOF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_48_lMT_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_49_lPARC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_50_lPARH_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_51_lPOPE_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_52_lPORB_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_53_lPTRI_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_54_lPCAL_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_55_lPSTC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_56_lPC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_57_lPREC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_58_lPCUN_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_59_lRAC_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_60_lRMF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_61_lSF_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_62_lSP_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_63_lST_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_64_lSMAR_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_65_lTP_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% 'fc_66_lTT_resampled_roi_avg_G0.4_sigma0.001_ficprior_nn5_8mins.hdf5',...
% };
% 
% fcPathsFICPost = {'fc_1_rBSTS_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_2_rCAC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_3_rCMF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_4_rCUN_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_5_rENT_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_6_rFP_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_7_rFUS_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_8_rIP_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_9_rIT_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_10_rISTC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_11_rLOCC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_12_rLOF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_13_rLING_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_14_rMOF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_15_rMT_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_16_rPARC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_17_rPARH_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_18_rPOPE_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_19_rPORB_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_20_rPTRI_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_21_rPCAL_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_22_rPSTC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_23_rPC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_24_rPREC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_25_rPCUN_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_26_rRAC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_27_rRMF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_28_rSF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_29_rSP_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_30_rST_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_31_rSMAR_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_32_rTP_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_33_rTT_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_34_lBSTS_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_35_lCAC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_36_lCMF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_37_lCUN_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_38_lENT_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_39_lFP_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_40_lFUS_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_41_lIP_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_42_lIT_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_43_lISTC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_44_lLOCC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_45_lLOF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_46_lLING_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_47_lMOF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_48_lMT_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_49_lPARC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_50_lPARH_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_51_lPOPE_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_52_lPORB_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_53_lPTRI_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_54_lPCAL_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_55_lPSTC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_56_lPC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_57_lPREC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_58_lPCUN_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_59_lRAC_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_60_lRMF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_61_lSF_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_62_lSP_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_63_lST_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_64_lSMAR_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_65_lTP_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% 'fc_66_lTT_resampled_roi_avg_G0.4_sigma0.001_ficpost_nn5_8mins.hdf5',...
% };
% 
% 
% 
% scEmpPath = '../../data/connectivity_998/Hagmann_998.hdf5';
% fcEmpPath = '../../data/connectivity_66/Hagmann_66.hdf5';
% scEmp = h5read(scEmpPath,'/C_resampled');
% scEmpLen = weight_conversion(scEmp, 'lengths');
% t = load('../../results/66/optimalG_hag_66_resampled_fic_dt1_sigma0.001_8mins_EI.mat','fcs');
% fcEmp = t.fcs{16};
% for i = 2:5
% fcEmp = fcEmp + t.fcs{16,i};
% end
% fcEmp = fcEmp ./ 5;
% clearvars t;
% % fcEmp = h5read(fcEmpPath,'/CC');
% % nAreas = size(fcEmp,1);
% % fcEmp(1:nAreas+1:nAreas^2) = 1;
% 
% % Node Betweenness Centrality
% nbc_998 = betweenness_wei(scEmpLen);
% %Clustering Coefficient
% clstrCoef_998 = clustering_coef_wd(scEmp);
% %Participation Coefficient
% [commStrucSCEmp_998,modulSCEmp_998] = community_louvain(scEmp,1);
% partCoefSCEmp_998 = participation_coef(scEmp,commStrucSCEmp_998,1);
% partCoefSCEmpNbrs_998 = zeros(size(partCoefSCEmp_998));
% lesionStrengths = zeros(length(scPaths),1);
% modulsFICPrior = zeros(length(fcPathsFICPrior),1);
% modulsFICPost = zeros(length(fcPathsFICPost),1);
% fcCorrsFICPrior = zeros(length(fcPathsFICPrior),1);
% fcCorrsFICPost = zeros(length(fcPathsFICPost),1);
% fcCorrsLesionedFICPrior = zeros(length(fcPathsFICPrior),1);
% fcCorrsLesionedFICPost = zeros(length(fcPathsFICPost),1);
% fcDistancePrior = zeros(length(fcPathsFICPrior),1);
% fcDistancePost = zeros(length(fcPathsFICPost),1);
% partCoefSCEmp  = zeros(length(fcPathsFICPost),1);
% nbc  = zeros(length(fcPathsFICPost),1);
% zscrPrior = zeros(length(fcPathsFICPrior),1);
% zscrPost = zeros(length(fcPathsFICPost),1);
% for i = 1:length(fcPathsFICPrior)
%     avgFCPrior = h5read(['../../results/66/' fcPathsFICPrior{i}],'/avgCC');
%     avgFCPost = h5read(['../../results/66/' fcPathsFICPost{i}],'/avgCC');
%     LesionIdx = h5readatt(['../../data/connectivity_998/lesioned/' scPaths{i}],'/C_resampled','LesionIdx');
%     nbrs = h5read(['../../data/connectivity_998/lesioned/' scPaths{i}],'/Neighbours');
%     lesionStrengths(i) = lesion_strength(scEmp,nbrs);
%     partCoefSCEmp(i) = sum(partCoefSCEmp_998(nbrs));
%     nbc(i) = sum(nbc_998(nbrs));
% %     [commstrucFCPrior,modulFICPrior] = modularity_und(avgFCPrior);
% %     [commstrucFCPost,modulFICPost] = modularity_und(avgFCPost);
%     [commstrucFCPrior,modulFICPrior] = modularity_louvain_und_sign(avgFCPrior,'sta');
%     [commstrucFCPost,modulFICPost] = modularity_louvain_und_sign(avgFCPost,'sta');
%     modulsFICPrior(i) = modulFICPrior;
%     modulsFICPost(i) = modulFICPost;
% %     fcCorrsFICPrior(i) = find_corr(fcEmp,avgFCPrior);
% %     nbrs = h5read(scPaths{i},'/Neighbours');
%     fcCorrsLesionedFICPrior(i) = find_corr_lesioned(fcEmp,avgFCPrior,LesionIdx);
% %     fcCorrsFICPost(i) = find_corr(fcEmp,avgFCPost);
% %     nbrs = h5read(scPaths{i},'/Neighbours');
%     fcCorrsLesionedFICPost(i) = find_corr_lesioned(fcEmp,avgFCPost,LesionIdx);
%     fcDistancePrior(i) = fc_distance(avgFCPrior,fcEmp,LesionIdx);
%     fcDistancePost(i) = fc_distance(avgFCPost,fcEmp,LesionIdx);
% %     t = compute_zscores(fc_hc_sim,avgFCPrior);
% %     zscrPrior(i) = size(find(abs(t)>2),1);
% %     t = compute_zscores(fc_hc_sim,avgFCPost);
% %     zscrPost(i) = size(find(abs(t)>2),1);
% end
% 
% figure();
% subplot(2,3,1);
% hold on;
% xlabel('Lesion Strength')
% ylabel('FC\_Emp vs FC\_Sim Correlation')
% [rho1,pVal1] = corrcoef(lesionStrengths,fcCorrsLesionedFICPrior);
% rho1 = rho1(1,2);
% pVal1 = pVal1(1,2);
% p=polyfit(lesionStrengths,fcCorrsLesionedFICPrior,1);
% pred = polyval(p,lesionStrengths);
% plot(lesionStrengths,fcCorrsLesionedFICPrior,'ko');
% plot(lesionStrengths,pred,'k');
% gtext(['r=',sprintf('%.2f, ',rho1),'p=',sprintf('%.2f ',pVal1)],'FontSize',13,'Color','k');
% 
% [rho2,pVal2] = corrcoef(lesionStrengths,fcCorrsLesionedFICPost);
% rho2 = rho2(1,2);
% pVal2 = pVal2(1,2);
% p=polyfit(lesionStrengths,fcCorrsLesionedFICPost,1);
% pred = polyval(p,lesionStrengths);
% plot(lesionStrengths,fcCorrsLesionedFICPost,'bo');
% plot(lesionStrengths,pred,'b');
% gtext(['r=',sprintf('%.2f, ',rho2),'p=',sprintf('%.2f ',pVal2)],'FontSize',13,'Color','b');
% 
% subplot(2,3,2)
% hold on;
% xlabel('Centrality')
% ylabel('FC\_Emp vs FC\_Sim Correlation')
% [rho1,pVal1] = corrcoef(nbc,fcCorrsLesionedFICPrior);
% rho1 = rho1(1,2);
% pVal1 = pVal1(1,2);
% p=polyfit(nbc,fcCorrsLesionedFICPrior,1);
% pred = polyval(p,nbc);
% plot(nbc,fcCorrsLesionedFICPrior,'ko');
% plot(nbc,pred,'k');
% gtext(['r=',sprintf('%.2f, ',rho1),'p=',sprintf('%.2f ',pVal1)],'FontSize',13,'Color','k');
% 
% [rho2,pVal2] = corrcoef(nbc,fcCorrsLesionedFICPost);
% rho2 = rho2(1,2);
% pVal2 = pVal2(1,2);
% p=polyfit(nbc,fcCorrsLesionedFICPost,1);
% pred = polyval(p,nbc);
% plot(nbc,fcCorrsLesionedFICPost,'bo');
% plot(nbc,pred,'b');
% gtext(['r=',sprintf('%.2f, ',rho2),'p=',sprintf('%.2f ',pVal2)],'FontSize',13,'Color','b');
% 
% subplot(2,3,3);
% hold on;
% xlabel('Paticipation Coefficient')
% ylabel('FC\_Emp vs FC\_Sim Correlation')
% [rho1,pVal1] = corrcoef(partCoefSCEmp,fcCorrsLesionedFICPrior);
% rho1 = rho1(1,2);
% pVal1 = pVal1(1,2);
% p=polyfit(partCoefSCEmp,fcCorrsLesionedFICPrior,1);
% pred = polyval(p,partCoefSCEmp);
% plot(partCoefSCEmp,fcCorrsLesionedFICPrior,'ko');
% plot(partCoefSCEmp,pred,'k');
% gtext(['r=',sprintf('%.2f, ',rho1),'p=',sprintf('%.2f ',pVal1)],'FontSize',13,'Color','k');
% 
% [rho2,pVal2] = corrcoef(partCoefSCEmp,fcCorrsLesionedFICPost);
% rho2 = rho2(1,2);
% pVal2 = pVal2(1,2);
% p=polyfit(partCoefSCEmp,fcCorrsLesionedFICPost,1);
% pred = polyval(p,partCoefSCEmp);
% plot(partCoefSCEmp,fcCorrsLesionedFICPost,'bo');
% plot(partCoefSCEmp,pred,'b');
% gtext(['r=',sprintf('%.2f, ',rho2),'p=',sprintf('%.2f ',pVal2)],'FontSize',13,'Color','b');
% 
% 
% subplot(2,3,4);
% hold on;
% xlabel('Lesion Strength')
% ylabel('FC Distance')
% [rho1,pVal1] = corrcoef(lesionStrengths,fcDistancePrior);
% rho1 = rho1(1,2);
% pVal1 = pVal1(1,2);
% p=polyfit(lesionStrengths,fcDistancePrior,1);
% pred = polyval(p,lesionStrengths);
% plot(lesionStrengths,fcDistancePrior,'ko');
% plot(lesionStrengths,pred,'k');
% gtext(['r=',sprintf('%.2f, ',rho1),'p=',sprintf('%.2f ',pVal1)],'FontSize',13,'Color','k');
% 
% [rho2,pVal2] = corrcoef(lesionStrengths,fcDistancePost);
% rho2 = rho2(1,2);
% pVal2 = pVal2(1,2);
% p=polyfit(lesionStrengths,fcDistancePost,1);
% pred = polyval(p,lesionStrengths);
% plot(lesionStrengths,fcDistancePost,'bo');
% plot(lesionStrengths,pred,'b');
% gtext(['r=',sprintf('%.2f, ',rho2),'p=',sprintf('%.2f ',pVal2)],'FontSize',13,'Color','b');
% 
% subplot(2,3,5)
% hold on;
% xlabel('Centrality')
% ylabel('FC Distance')
% [rho1,pVal1] = corrcoef(nbc,fcDistancePrior);
% rho1 = rho1(1,2);
% pVal1 = pVal1(1,2);
% p=polyfit(nbc,fcDistancePrior,1);
% pred = polyval(p,nbc);
% plot(nbc,fcDistancePrior,'ko');
% plot(nbc,pred,'k');
% gtext(['r=',sprintf('%.2f, ',rho1),'p=',sprintf('%.2f ',pVal1)],'FontSize',13,'Color','k');
% 
% [rho2,pVal2] = corrcoef(nbc,fcDistancePost);
% rho2 = rho2(1,2);
% pVal2 = pVal2(1,2);
% p=polyfit(nbc,fcDistancePost,1);
% pred = polyval(p,nbc);
% plot(nbc,fcDistancePost,'bo');
% plot(nbc,pred,'b');
% gtext(['r=',sprintf('%.2f, ',rho2),'p=',sprintf('%.2f ',pVal2)],'FontSize',13,'Color','b');

% subplot(2,3,6);
% hold on;
% xlabel('Paticipation Coefficient')
% ylabel('FC Distance')
% [rho1,pVal1] = corrcoef(partCoefSCEmp,fcDistancePrior);
% rho1 = rho1(1,2);
% pVal1 = pVal1(1,2);
% p=polyfit(partCoefSCEmp,fcDistancePrior,1);
% pred = polyval(p,partCoefSCEmp);
% plot(partCoefSCEmp,fcDistancePrior,'ko');
% plot(partCoefSCEmp,pred,'k');
% gtext(['r=',sprintf('%.2f, ',rho1),'p=',sprintf('%.2f ',pVal1)],'FontSize',13,'Color','k');
% 
% [rho2,pVal2] = corrcoef(partCoefSCEmp,fcDistancePost);
% rho2 = rho2(1,2);
% pVal2 = pVal2(1,2);
% p=polyfit(partCoefSCEmp,fcDistancePost,1);
% pred = polyval(p,partCoefSCEmp);
% plot(partCoefSCEmp,fcDistancePost,'bo');
% plot(partCoefSCEmp,pred,'b');
% gtext(['r=',sprintf('%.2f, ',rho2),'p=',sprintf('%.2f ',pVal2)],'FontSize',13,'Color','b');


load '../../results/66/graph_metrics.mat';
t = [1;3;5;7;8;9;11;15;17;18;19;20;21;22;24;27;30;31;32;33];
idxs = [t;t+33];
clearvars t;

[rho1,pVal1] = corrcoef(partCoefSCEmp(idxs),fcDistancePrior(idxs));
rho1 = rho1(1,2);
pVal1 = pVal1(1,2);
p=polyfit(partCoefSCEmp(idxs),fcDistancePrior(idxs),1);
pred = polyval(p,partCoefSCEmp(idxs));
plot(partCoefSCEmp(idxs),fcDistancePrior(idxs),'ko','MarkerFaceColor','k','MarkerSize',3);
hold on;
plot(partCoefSCEmp(idxs),pred,'k');
box off;
xlabel('Paticipation Coefficient','FontWeight','bold')
ylabel('FC Distance','FontWeight','bold')
ylim([2 3.5])
set(gca,'XTick',0:5:20,'YTick',2:0.5:3.55,'YTickLabel',{'2' '2.5' '3' '3.5'},'FontWeight','bold');
text(1,3.35,['r=',sprintf('%.2f, ',rho1),'p=',sprintf('%.2f ',pVal1)],'Color','k','FontSize',15);
% savePath = '../../reports/figures/gm1_resampled_roi_avg';


[rho2,pVal2] = corrcoef(partCoefSCEmp(idxs),fcDistancePost(idxs));
rho2 = rho2(1,2);
pVal2 = pVal2(1,2);
p=polyfit(partCoefSCEmp(idxs),fcDistancePost(idxs),1);
pred = polyval(p,partCoefSCEmp(idxs));
plot(partCoefSCEmp(idxs),fcDistancePost(idxs),'bo','MarkerFaceColor','b','MarkerSize',3);
% hold on;
plot(partCoefSCEmp(idxs),pred,'b');
% box off;
% xlabel('Paticipation Coefficient','FontWeight','bold')
% ylabel('FC Distance','FontWeight','bold')
% set(gca,'XTick',0:5:20,'YTick',2:0.5:3.55,'YTickLabel',{'2' '2.5' '3' '3.5'},'FontWeight','bold');
text(1,3.2,['r=',sprintf('%.2f, ',rho2),'p=',sprintf('%.2f ',pVal2)],'Color','b','FontSize',15);
savePath = '../../reports/figures/gm_resampled_roi_avg';